#!/bin/bash
source /root/.bashrc
/usr/local/bin/populate-user-data.sh

#sed -i "s/MB-IP/${MB_IP}/g" /mnt/apache-stratos-cartridge-agent/conf/jndi.properties
#sed -i "s/MB-PORT/${MB_PORT}/g" /mnt/apache-stratos-cartridge-agent/conf/jndi.properties

sed -i "s/MB-IP/${MB_IP}/g" /mnt/apache-stratos-cartridge-agent/conf/mqtttopic.properties
sed -i "s/MB-PORT/${MB_PORT}/g" /mnt/apache-stratos-cartridge-agent/conf/mqtttopic.properties

sed -i "s/CEP-IP/${CEP_IP}/g" /mnt/apache-stratos-cartridge-agent/bin/stratos.sh
sed -i "s/CEP-PORT/${CEP_PORT}/g" /mnt/apache-stratos-cartridge-agent/bin/stratos.sh

sed -i 's/CERT-TRUSTSTORE/${script_path}\/..\/security\/client-truststore.jks/g' /mnt/apache-stratos-cartridge-agent/bin/stratos.sh
sed -i "s/TRUSTSTORE-PASSWORD/wso2carbon/g" /mnt/apache-stratos-cartridge-agent/bin/stratos.sh


export JAVA_HOME=/opt/java
export PATH=$PATH:$JAVA_HOME/bin
cd /mnt/apache-stratos-cartridge-agent/bin/;./stratos.sh & > /tmp/agent.log
/usr/sbin/apache2ctl -D FOREGROUND
